### ISSUE TITLE
No exported member 'CowSdk'

### ISSUE THREAD

**Issue by paschal533** [cowprotocol/cow-sdk#110]
Hi, I'm trying to use cow-sdk in my project, but I'm getting this error message
```
Module '"@cowprotocol/cow-sdk"' has no exported member 'CowSdk'
```

I installed cowprotocol/cow-sdk using this command line
```
npm install @cowprotocol/cow-sdk
```

Then I imported CowSdk using this line of code

```
import { CowSdk, OrderKind } from '@cowprotocol/cow-sdk'
```

But, I'm getting this error message

```
Module '"@cowprotocol/cow-sdk"' has no exported member 'CowSdk'
```

**Comment by anxolin** [comment]
Hi! can you try with the new version released today please?


📎 README: https://github.com/cowprotocol/cow-sdk/blob/main/README.md
📚 SDK docs website: https://docs.cow.fi/cow-sdk


Let us know how it goes!

**Comment by anxolin** [comment]
Closing the issue as we believe it should be fixed, but please reopen if its not the case.
