### ISSUE TITLE
Missing type on OrderQuoteSide.kind

### ISSUE THREAD

**Issue by arodundef** [cowprotocol/cow-sdk#134]
According to your API documentation [here](https://docs.cow.fi/cow-sdk/sign-and-post-orders/step-1-get-market-price). I could use in the `getQuote` function the `OrderKind.SELL` or `OrderKind.BUY`.

But, it is impossible because `kind` only accepts `OrderQuoteSide` enum, as in the following image. 
![image](https://github.com/cowprotocol/cow-sdk/assets/90649201/a085c2f0-e694-4dfb-a718-5bda11dd5c8f)

Then, I have to use `OrderQuoteSide.kind` instead `OrderKind`. 

## And there is the second issue
`OrderQuoteSide.kind` has only `SELL` enum, not the buy one. So, it's impossible to use `OrderQuoteSide.kind.BUY`. As the images below:
![image](https://github.com/cowprotocol/cow-sdk/assets/90649201/570df636-0db6-4029-aabe-f5ca999576ee)
![image](https://github.com/cowprotocol/cow-sdk/assets/90649201/254f5aac-f42d-433e-8d46-d47382fea6a8)

> cow-sdk/dist/order-book/generated/models/OrderQuoteSide.d.ts#L2

I'm using the `@cowprotocol/cow-sdk@^2.3.0-rc.7`
I tried to help with a [PR](https://github.com/cowprotocol/cow-sdk/pull/133), but @mfw78 told me that is not the right place to change it. Feel free to refuse that.

**Comment by alfetopito** [comment]
Hey, thanks for reporting!
Indeed, that [PR](https://github.com/cowprotocol/cow-sdk/pull/133/files) is modifying an auto-generated file.
It's generated based on the [services repo openapi specs](https://github.com/cowprotocol/services/blob/main/crates/orderbook/openapi.yml).

The issue you mentioned might come from this line I guess https://github.com/cowprotocol/services/blob/main/crates/orderbook/openapi.yml#L1161

It could either be that the openapi specs it incorrect or something in the auto-generation that's broken.

I'll raise this internally with the team.

**Comment by alfetopito** [comment]
Seems like indeed the code generation lib is to blame https://github.com/ferdikoomen/openapi-typescript-codegen/issues/1424

**Comment by alfetopito** [comment]
Not done yet, still pending the [PR](https://github.com/cowprotocol/cow-sdk/pull/138) approval/merge and a new version release

**Comment by alfetopito** [comment]
Released on 2.3.1 https://www.npmjs.com/package/@cowprotocol/cow-sdk?activeTab=versions
