### ISSUE TITLE
InsufficientBalance: order owner must have funds worth at least x in his account

### ISSUE THREAD

**Issue by yussdev** [cowprotocol/cow-sdk#215]
I'm getting this error when calling the `signOrder`:
`body: {
    errorType: 'InsufficientBalance',
    description: 'order owner must have funds worth at least x in his account'
  }`

**Comment by msied** [comment]
Am having the same issue. Please advise

**Comment by yussdev** [comment]
Hi, please check here:
https://discord.com/channels/869166959739170836/1258455317671579839/1259832909263671367

**Comment by alfetopito** [comment]
Summary of the issue/fix:

The order data being signed was different that what was submitted to the orderbook api.
That resulted in a different account address being recovered, which did not have the funds to trade, thus the error message.

We've updated the order signing tutorial to account for common pitfalls and should be able to give you accurate steps to sign and post the order https://learn.cow.fi/tutorial/getting-started-order
