### ISSUE TITLE
Chain Id and Prod/Barn environments improvements

### ISSUE THREAD

**Issue by ramirotw** [cowprotocol/cow-sdk#30]
1. Make chain id optional in the constructor and default to mainnet
2. Add an optional `options` param on each API method where we can set the chainId and the env (prod/barn)
3. The API methods should query both prod & barn environments so we abstract them away from the user

**Comment by anxolin** [comment]
Great to see these changes. I would just add that we should have a way to change the initial defaults from the constructor

This way, we hav two ways of using the SDK
- Always providing the options
- ..or, dapps can change the default network when this one changes

**Comment by ramirotw** [comment]
> 3\. The API methods should query both prod & barn environments so we abstract them away from the user

@matextrem lets pause the env merging so we can discuss about the pagination
