### ISSUE TITLE
Make the production API env be the 1st option to query instead of barn

### ISSUE THREAD

**Issue by ramirotw** [cowprotocol/cow-sdk#46]
## Description

PR https://github.com/cowprotocol/cow-sdk/pull/42 introduced querying in both environments: prod & barn. The problem was that barn was left as the 1st option and it should be prod.

**Comment by matextrem** [comment]
It was already fixed here https://github.com/cowprotocol/cow-sdk/pull/42/commits/add77eb952590d8f332c65fb98f1066a04ccafb7#diff-f0f1614bb2fa989331ed20b1d3fe58f2458d850d001d06440d5de7e4a664d829R408

Should we close this issue ?

**Comment by ramirotw** [comment]
Left a comment in the PR
