### ISSUE TITLE
Export constants in the next version

### ISSUE THREAD

**Issue by adamazad** [cowprotocol/cow-sdk#62]
I use a SDK as a building block for https://github.com/levelkdev/swapr-sdk. I need to access to the settlement contract address. Thanks :)

**Comment by alfetopito** [comment]
Deployed on https://github.com/cowprotocol/cow-sdk/releases/tag/v1.0.0-RC.6

https://www.npmjs.com/package/@cowprotocol/cow-sdk/v/1.0.0-RC.6
