### ISSUE TITLE
Partially Fillable Comment

### ISSUE THREAD

**Issue by kimpurcell** [cowprotocol/cow-sdk#77]
Is the "true" and "false" incorrect in https://github.com/cowprotocol/cow-sdk/blob/main/docs/post-order-example.ts? 

Shouldn't false mean "Fill or Kill" and true mean "Partial execution"?
Instead, this is what's stated in the code:

  partiallyFillable: false, // (**true** would be for a "Fill or Kill" order, "**false**" for allowing "Partial execution" which is not supported yet)

**Comment by ramirotw** [comment]
hey @kimpurcell you are absolutely right!
