### ISSUE TITLE
`Can't import the named export 'createReferrerMetadata' (imported as 'f') from default-exporting module (only default export is available)`

### ISSUE THREAD

**Issue by adamazad** [cowprotocol/cow-sdk#91]
Hey! 

We're upgrading the SDK's dependency on Swapr. We ran into the following error when running `npm run build`:

> Can't import the named export 'createReferrerMetadata' (imported as 'f') from default-exporting module (only default export is available)

I suspected Swapr's old setup. So tried it on a fresh CRA and the command above yielded the same error. Do you have any suggestions on how to resolve this?

SDK version [@cowprotocol/cow-sdk@1.0.1-RC.8](https://www.npmjs.com/package/@cowprotocol/cow-sdk/v/1.0.1-RC.8)

**Comment by bh2smith** [comment]
@shoom3301 - I think that this may have something to do with recent changes to the App Data, but I am not quite sure what is up here. Since you appear to be "closest to this code" I thought you might have some insights:

Here is a repo making use of this project which fails on build with the error described above.

https://github.com/adamazad/cow-sdk-app

**Comment by alfetopito** [comment]
We've had something similar in the past when using it on NodeJS.

I'll take a look at https://github.com/adamazad/cow-sdk-app and see if I can figure out what's wrong.

**Comment by alfetopito** [comment]
Turns out this is taking me more than expected to get anywhere.
We'll need to spend some time to properly debug the issue.

**Comment by adamazad** [comment]
> Turns out this is taking me more than expected to get anywhere. We'll need to spend some time to properly debug the issue.

What's the ETA on this? 😬

**Comment by alfetopito** [comment]
> > Turns out this is taking me more than expected to get anywhere. We'll need to spend some time to properly debug the issue.
> 
> What's the ETA on this? 😬

I had to finish work on something else and didn't continue the investigation yesterday.
Now as I understand this is blocking you, I'll focus on this.

No promises on ETA as I'm not sure exactly what's wrong.

**Comment by alfetopito** [comment]
Good news and bad news.

Good: I figured out what's wrong (more of less) and the build in your example succeeds.
Will send a PR soon fixing it in our libs.

Bad: Now running the app several warnings/errors are thrown for various dependencies. I suspect it might be something with your Webpack config, as we get none of that on the current version.
The app works fine though, so you might be able to ignore it...

![Screenshot 2022-12-27 at 14 45 51](https://user-images.githubusercontent.com/43217/209683033-7607e0d6-59b2-43d9-ad33-d08faa2e9bdf.png)

Anyway, ETA is as soon as I can prepare the PR and get the required approvals. This might be tricky as most of the team is on holidays. I'll keep you posted.

**Comment by bh2smith** [comment]
@alfetopito - I would be happy to blindly approve whatever you need if it helps!

**Comment by adamazad** [comment]
> Bad: Now running the app several warnings/errors are thrown for various dependencies. I suspect it might be something with your Webpack config, as we get none of that on the current version.
> The app works fine though, so you might be able to ignore it...

That's from react scripts not being able to find the source maps. You can disable them setting `GENERATE_SOURCEMAP=false` in your environment. Good work!

**Comment by alfetopito** [comment]
> @alfetopito - I would be happy to blindly approve whatever you need if it helps!

Appreciate it, Ben! But your approval might not count =P

**Comment by alfetopito** [comment]
Here's the first PR https://github.com/cowprotocol/app-data/pull/21
Once that's merged and published to NPM, I'll need to update cow-sdk and publish another version of it

**Comment by alfetopito** [comment]
@adamazad please try it now with this version https://www.npmjs.com/package/@cowprotocol/cow-sdk/v/1.0.2-RC.0
